name: JReleaser

description: 'Release Java projects quickly and easily with JReleaser'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:

  version:
    description: 'The version of JReleaser to download and execute.'
    default: 'early-access'
    required: true

  arguments:
    description: 'The command-line arguments to be passed to JReleaser.'
    default: 'full-release'
    required: true

  working-directory:
    required: true
    default: ${{ github.workspace }}
    description: 'The directory to change into.'

runs:
  using: 'composite'
  steps:
    - name: 'Download JReleaser'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::📦 Download JReleaser"
        java "${{ github.action_path }}/copy.java" ${{ inputs.version }}
        java -jar jreleaser-cli.jar --version
        echo "::endgroup::"

    - name: 'Execute JReleaser'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "☕ java -jar jreleaser-cli.jar ${{ inputs.arguments }}"
        java -jar jreleaser-cli.jar ${{ inputs.arguments }}
