name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: 'Java ${{ matrix.java }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-14, windows-latest ]
        java: [ 11, 17, 21 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu

      - uses: ./
        with:
          arguments: --version
